{% set _version_match = load_file_regex(
  load_file="qpytorch/version.py",
  regex_pattern="__version__ = version = '(.+)'"
) %}
{% set version = _version_match[1] %}

package:
  name: qpytorch
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: "$PYTHON ./setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python>=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pytorch
    - pip

  run:
    - python >=3.10
    - pytorch >=2.0
    - jaxtyping
    - mpmath >=0.19,<=1.3
    - scikit-learn
    - scipy >=1.6.0
    - linear_operator >=0.6
    - gpytorch >=1.13
    - numpy <2

test:
  imports:
    - qpytorch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://lanzithinking.github.io/QePyTorch/
  license: MIT
  license_file: LICENSE
  summary: An implementation of Q-Exponential Processes in Pytorch built from GPyTorch
  doc_url: https://qepytorch.readthedocs.io/en/latest/
  dev_url: https://github.com/lanzithinking/qepytorch
